# Generated by Django 5.2.4 on 2025-08-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='date_to',
        ),
    ]
